# Generated by Django 5.0.1 on 2024-01-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='home_cover',
            field=models.ImageField(blank=True, default={'STATIC_URL': '/static/'}, null=True, upload_to='home_cover', verbose_name='Home cover'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='product_cover',
            field=models.ImageField(blank=True, default={'STATIC_URL': '/static/'}, null=True, upload_to='product_cover', verbose_name='Product cover'),
        ),
    ]
