# Generated by Django 5.0.1 on 2024-02-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_sitesetting_slogan_alter_sitesetting_home_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='banner_best_products',
            field=models.ImageField(blank=True, null=True, upload_to='banner_best_products', verbose_name='Best products Picture'),
        ),
    ]
