# Generated by Django 5.0.1 on 2024-02-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_description'),
        ('setting', '0004_sitesetting_banner_best_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('categories', models.ManyToManyField(blank=True, to='product.category', verbose_name='Categories')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.link', verbose_name='Link')),
            ],
        ),
    ]
