# Generated by Django 5.0.1 on 2024-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_sitesetting_home_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postersetting',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default=1, max_length=100, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
