# Generated by Django 5.0.1 on 2024-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('physic', 'Physical'), ('company', 'Company'), ('passenger', 'Passenger')], default='physic', max_length=100),
        ),
    ]
