# Generated by Django 5.0.1 on 2024-01-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_orderitem_item'),
        ('product', '0004_brand_product_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='OrderItem',
        ),
    ]
